nameOverride: ""
fullnameOverride: ""

host:
pullPolicy: IfNotPresent

ingress: 
  enabled: true

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: "1000m"
    memory: "1Gi"
  requests:
    cpu: "10m"
    memory: "32Mi"

adminWeb:
  enabled: true
  name: admin-web
  image:
    repository: registry.cn-beijing.aliyuncs.com/36node/fcp-admin-web
    # Overrides the image tag whose default is the chart appVersion.
    tag: main
  env:
    build: "20210712-000000"
    copyright: "36node 出品"
    loginFailLockSeconds: "300"

    authEndpoint: ""
    fcpEndpoint: ""
    mapEndpoint: ""
    dahuaMqttRobotEndpoint: ""
    illegalExpiresDays: "5"
    draftExpiresDays: "2"

    mapBoundNorthEast: "30.7184163,120.47437365"
    mapBoundSouthWest: "28.92927024,122.31013782"
    mapCenter: "29.85645453,121.51695313"
    mapCurrentZoom: "11"

    mapGantryMinZoom: "11"
    mapMaxZoom: "17"
    mapMinZoom: "11"

    mqttUrl:
    mqttTopicNotifyWarning:

    ossAccessKeyId:
    ossAccessKeySecret:
    ossBucket:
    ossEndpoint:
    ossDomain:
    ossForcePathStyle:
    ossRegion:

    provider: ""
    scope: ""

    title: ""
    version: "0.0"
 
  resources:
  service:
    port:
    type:

api:
  enabled: true
  name: api
  image:
    repository: registry.cn-beijing.aliyuncs.com/36node/fcp-core-api
    # Overrides the image tag whose default is the chart appVersion.
    tag: main
  replicas: 1
  path: /ecs-api
  env:
    cacheRedisUri: "redis://localhost:6379"

    illegalExpires: "259200000"
    illegalExpiresDays: "5"
    draftExpiresDays: "2"
    illegalRecordClean: "31536000"
    illegalDraftClean: "2592000"
    healthStatClean: "604800"
    illegalUnderspeedLimit: "60"
    logLevel: "log"

    memcachedUri: "memcached://localhost:11211"
    microserviceEnable: "true"
    mongoUri: "mongodb://localhost/api"
    mqttUri: "mqtt://localhost:1883"
    mqttUsername: 
    mqttPassword:
    mqttTopicIllegalRecord: "fcp/illegal"
    mqttTopicIllegalDraft: "fcp/draft"
    mqttTopicTrackRecord: "fcp/track"
    mqttTopicGantryDevice: "notify/gantry-device"
    mqttTopicGantry: "notify/gantry"
    mqttTopicIllegalType: notify/illegal-type
    mqttTopicNotifyWarning: "notify/warning"
    mqttTopicNotifyIllegalRecord: "notify/illegal"

    port: "80"

    trackRecordClean: "259200"
    
    vehicleImportClean: "604800"
    vehicleImportDelay: "1000"
    vehicleImportLimit: "500"
    vehicleImportPath: "./uploads"
    illegalWarningLimit: "60"
    warningClean: "31536000"
  resources:
    limits:
      cpu: "1"
      memory: "2G"
    requests:
      cpu: "500m"
      memory: "1G"
  service:
    port:
    type:

auth:
  enabled: true
  name: auth
  image:
    repository: registry.cn-beijing.aliyuncs.com/36node/stargate-auth
    tag: main
  replicas: 1
  path: /auth/v1
  env:
    port: "80"
    mongoUri: "mongodb://localhost/auth"
  service:
    port:
    type:

robotDahua:
  enabled: false
  name: robot-dahua
  path: /dahua-mqtt-robot
  mock:
    name: robot-dahua-mock
    enabled: false
  image:
    repository: registry.cn-beijing.aliyuncs.com/36node/fcp-dahua-mqtt-robot
    tag: main
  replicas: 1
  env:
    nodeEnv: development
    logLevel: "info"
    sourceName: 大华
    name: 大华MQTT数据源
    port: 80
    fcpEndpoint: http://fcp-uat.36node.com/ecs-api
    robotEndpoint: http://fcp-uat.36node.com/dahua-mqtt-robot
    redisUri: redis://localhost:6379
    redisGlobalPrefix: DAHUA-ROBOT-
    draftExpireDays: "2"
    mqttUri: mqtt://localhost
    mqttUsername: 
    mqttPassword: 
    mqttTopicIllegalRecord: fcp/illegal
    mqttTopicTrackRecord: fcp/track
    mqttTopicIllegalDraft: fcp/draft
    mqttTopicIllegalRecordDahua: record/illegal/dahua
    mqttTopicTrackRecordDahua: record/track/dahua
    mqttTopicGantryDevice: notify/gantry-device/#
    mqttTopicGantry: notify/gantry/#
    mqttTopicIllegalType: notify/illegal-type/#
    mockTrackTimeInterval: "100"
  resources:
  service:
    port: 80
    type:

robotHengtong:
  enabled: false
  name: robot-hengtong
  path: /hengtong-illegal-robot
  mock:
    name: robot-hengtong-mock
    enabled: false
  image:
    repository: registry.cn-beijing.aliyuncs.com/36node/fcp-hengtong-robot
    tag: main
  replicas: 1
  env:
    logLevel: "info"
    sourceName: 恒通
    name: 恒通违法变道
    draftExpireDays: "2"
    mqttPassword: 
    mqttUri: "mqtt://localhost"
    mqttUsername: 
    mqttTopicIllegalRecord: "fcp/illegal"
    mqttTopicIllegalDraft: "fcp/draft"
    mqttTopicGantryDevice: notify/gantry-device/#
    mqttTopicGantry: notify/gantry/#
    mqttTopicIllegalType: notify/illegal-type/#
    redisGlobalPrefix: HENGTONG-ROBOT-
    redisUri: redis://localhost:6379
    robotEndpoint: http://fcp-uat.36node.com/hengtong-illegal-robot
    fcpEndpoint: http://fcp-uat.36node.com/ecs-api
    nodeEnv: "development"
    port: 80
  resources:
  service:
    port: 80
    type:

robotFace:
  enabled: false
  name: robot-face
  path: /face-robot
  mock:
    name: robot-face-mock
    enabled: false
  image:
    repository: registry.cn-beijing.aliyuncs.com/36node/fcp-face-robot
    tag: main
  replicas: 1
  env:
    logLevel: "info"
    sourceName: 恒通
    name: 恒通人脸比对
    mqttPassword: 
    mqttUri: "mqtt://localhost"
    mqttUsername: 
    mqttTopicGantryDevice: notify/gantry-device/#
    mqttTopicGantry: notify/gantry/#
    mqttTopicIllegalRecordPersonCreate: notify/illegal/PERSON/create
    mqttTopicIllegalRecordNonmotorCreate: notify/illegal/NONMOTOR/create
    mqttTopicIllegalRecordPersonUpdate: notify/illegal/PERSON/update
    mqttTopicIllegalRecordNonmotorUpdate: notify/illegal/NONMOTOR/update
    mqttTopicIllegalRecordPersonDelete: notify/illegal/PERSON/delete
    mqttTopicIllegalRecordNonmotorDelete: notify/illegal/NONMOTOR/delete
    mqttTopicIllegalRecordPersonClose: notify/illegal/PERSON/close
    mqttTopicIllegalRecordNonmotorClose: notify/illegal/NONMOTOR/close
    mqttNotifyPerson: record/person/face
    mqttTopicWarning: record/warning/face
    redisGlobalPrefix: FACE-ROBOT-
    redisUri: redis://localhost:6379
    robotEndpoint: http://fcp-uat.36node.com/face-robot
    fcpEndpoint: http://fcp-uat.36node.com/ecs-api
    nodeEnv: "development"
    port: 80
  resources:
  service:
    port: 80
    type:

robotXindian:
  enabled: false
  name: robot-xindian
  path: /xindian-robot
  image:
    repository: registry.cn-beijing.aliyuncs.com/36node/fcp-xindian-robot
    tag: main
  replicas: 1
  env:
    mqttUsername: ""
    mqttPassword: ""
    mqttTopicIllegalRecord: "notify/illegal/VEHICLE/create"
    mqttUri: "mqtt://localhost:1883"
    redisUri: redis://localhost:6379
    redisGlobalPrefix: XINDIAN-ROBOT-
    port: 80
    logLevel: "info"
    name: 信电
    robotEndpoint: http://fcp-uat.36node.com/xindian-robot
    fcpEndpoint: http://fcp-uat.36node.com/ecs-api
    recordDefaultJyzt: "0"
    recordDefaultSpotsn: ""
    recordDefaultUpuser: ""
    sqlDatabase: "ZJVIO_NB"
    sqlHost: "192.168.101.11"
    sqlUsername: "ZJVIO_NB"
    sqlPassword: "ZJVIO_NB@2022"
    sqlPoolSize: "20"
    sqlPort: "1521"
    sqlSequenceQuery: "SELECT VIO_TEMP_SEQ.NEXTVAL FROM DUAL"
    sqlServicename: "EE.oracle.docker"
    sqlSync: "false"
    sqlTableName: "VIO_TEMP_SURVEIL_FTP"
    sqlType: "oracle"
  resources:
    limits:
      cpu: "1"
      memory: "2G"
    requests:
      cpu: "500m"
      memory: "1G"
  service:
    port: 80
    type:

# mock:
#   enabled: false
#   name: mock
#   image:
#     repository: registry.cn-beijing.aliyuncs.com/36node/fcp-ecs-api
#     tag: main
#   replicas: 1
#   env:
#     mockData: "true"
#     mockIllegalDelay: "259200"
#     mockIllegalFirst: "false"
#     mockIllegalNum: "1"
#     mockImage: ""
#     mockTrackDelay: "60"
#     mockTrackNum: "3"
#     mockVideo: ""
#     mqttUri: "mqtt://localhost"

robotMock:
  enabled: false
  name: robot-mock
  image:
    repository: registry.cn-beijing.aliyuncs.com/36node/fcp-mock-robot
    tag: main
  replicas: 1
  env:
    logLevel: "info"
    mqttPassword: 
    mqttTopicIllegalRecord: fcp/illegal
    mqttTopicTrackRecord: fcp/track
    mqttUri: mqtt://localhost
    mqttUsername: 
    nodeEnv: "development"
    port: 80
    urlPrefix: "/v0"
    apiService: http://api/ecs-api
  resources:
  service:
    port:
    type:
