# Default values for map.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: consbio/mbtileserver
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 0.8.2

nameOverride: ""
fullnameOverride: ""

host:
port: 80
path: /ecs-map
filePath: /opt/map
dirPath: /opt/files # 本地磁盘路径

nodeSelector:
  kubernetes.io/hostname: worker

resources:
  limits:
    cpu: "1000m"
    memory: "1Gi"
  requests:
    cpu: "10m"
    memory: "32Mi"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts:
    - host:
      paths:
        - path: /ecs-map
          pathType: ImplementationSpecific
  tls: []
