{{- if .Values.faceRobot.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.faceRobot.name }}
  labels:
    {{- include "fcp.labels" . | nindent 4 }}
    app.kubernetes.io/component: face-robot
spec:
  type: {{ .Values.faceRobot.service.type | default .Values.service.type }}
  ports:
    - port: {{ .Values.faceRobot.service.port | default .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fcp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: face-robot
{{- end }}