{{- if .Values.adminWeb.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.adminWeb.name }}
  labels:
    {{- include "fcp.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin-web
spec:
  type: {{ .Values.adminWeb.service.type | default .Values.service.type }}
  ports:
    - port: {{ .Values.adminWeb.service.port | default .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: 
    {{- include "fcp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: admin-web
{{- end }}