{{- if .Values.etcRobot.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.etcRobot.name }}
  labels:
    {{- include "fcp.labels" . | nindent 4 }}
    app.kubernetes.io/component: etc-robot
spec:
  replicas: {{ .Values.etcRobot.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "fcp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: etc-robot
  template:
    metadata:
      {{- with .Values.etcRobot.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fcp.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: etc-robot
    spec:
      {{- include "fcp.images.pullSecrets" (dict "images" (list .Values.etcRobot.image) "global" .Values.global) | nindent 6 }}
      containers:
        - name: etc-robot
          image: {{ include "fcp.images.image" ( dict "imageRoot" .Values.etcRobot.image "global" .Values.global ) }}
          imagePullPolicy: {{ .Values.etcRobot.image.pullPolicy | default .Values.global.imagePullPolicy }}
          env:
            - name: URL_PREFIX
              value: {{ .Values.etcRobot.path }}
            {{- range $key, $value := .Values.etcRobot.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          ports:
            - name: http
              containerPort: 9527
              protocol: TCP
          resources:
            {{- toYaml .Values.etcRobot.resources | nindent 12 }}
      {{- with .Values.etcRobot.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.etcRobot.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.etcRobot.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}