{{- if .Values.dahuaMqttRobotMock.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.dahuaMqttRobotMock.name }}
  labels:
    {{- include "fcp.labels" . | nindent 4 }}
    app.kubernetes.io/component: dahua-mqtt-robot-mock
spec:
  replicas: {{ .Values.dahuaMqttRobotMock.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "fcp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: dahua-mqtt-robot-mock
  template:
    metadata:
      {{- with .Values.dahuaMqttRobotMock.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fcp.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: dahua-mqtt-robot-mock
    spec:
      {{- include "fcp.images.pullSecrets" (dict "images" (list .Values.dahuaMqttRobotMock.image) "global" .Values.global) | nindent 6 }}
      containers:
        - name: dahua-mqtt-robot-mock
          image: {{ include "fcp.images.image" ( dict "imageRoot" .Values.dahuaMqttRobotMock.image "global" .Values.global ) }}
          imagePullPolicy: {{ .Values.dahuaMqttRobotMock.image.pullPolicy | default .Values.global.imagePullPolicy }}
          env:
            {{- range $key, $value := .Values.dahuaMqttRobotMock.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          command: ["pnpm", "mock:prod"]
          ports:
            - name: http
              containerPort: 9527
              protocol: TCP
          resources:
            {{- toYaml .Values.dahuaMqttRobotMock.resources | nindent 12 }}
      {{- with .Values.dahuaMqttRobotMock.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dahuaMqttRobotMock.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dahuaMqttRobotMock.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}