{{- if .Values.adminWeb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.adminWeb.name }}
  labels:
    {{- include "admin-web.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.adminWeb.service.type | default .Values.service.type }}
  ports:
    - port: {{ .Values.adminWeb.service.port | default .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "admin-web.selectorLabels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.adminWeb.name }}
  labels:
    {{- include "fcp-ecs.labels" . | nindent 4 }}
    {{- include "admin-web.selectorLabels" . | nindent 4 }}
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "admin-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "admin-web.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Values.adminWeb.name }}
          image: "{{ .Values.adminWeb.image.repository }}:{{ .Values.adminWeb.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.adminWeb.image.pullPolicy | default .Values.pullPolicy }}
          env:
            - name: REACT_APP_AUTH_ENDPOINT
              value: "{{ .Values.adminWeb.env.authEndpoint }}"
            - name: REACT_APP_BUILD
              value: "{{ .Values.adminWeb.env.build }}"
            - name: REACT_APP_COPYRIGHT
              value: "{{ .Values.adminWeb.env.copyright }}"
            - name: REACT_APP_ECHO
              value: "{{ .Values.adminWeb.env.echo }}"
            - name: REACT_APP_ECS_ENDPOINT
              value: "{{ .Values.adminWeb.env.ecsEndpoint }}"
            - name: REACT_APP_GANTRY_ICON_SIZE
              value: "{{ .Values.adminWeb.env.gantryIconSize }}"
            - name: REACT_APP_GUANGXIN_ENDPOINT
              value: "{{ .Values.adminWeb.env.guangxinEndpoint }}"
            - name: REACT_APP_ILLEGAL_MONITOR_DAHUA_LIMIT
              value: "{{ .Values.adminWeb.env.illegalMonitorDahuaLimit }}"
            - name: REACT_APP_ILLEGAL_MONITOR_DAHUA_LIMIT_S
              value: "{{ .Values.adminWeb.env.illegalMonitorDahuaLimitS }}"
            - name: REACT_APP_ILLEGAL_MONITOR_DAHUA_LIMIT_S_DESC
              value: "{{ .Values.adminWeb.env.illegalMonitorDahuaLimitSDesc }}"
            - name: REACT_APP_ILLEGAL_MONITOR_FLASH_S
              value: "{{ .Values.adminWeb.env.illegalMonitorFlashS }}"
            - name: REACT_APP_ILLEGAL_MONITOR_HENGTONG_LIMIT
              value: "{{ .Values.adminWeb.env.illegalMonitorHengtongLimit }}"
            - name: REACT_APP_ILLEGAL_MONITOR_HENGTONG_LIMIT_S
              value: "{{ .Values.adminWeb.env.illegalMonitorHengtongLimitS }}"
            - name: REACT_APP_ILLEGAL_MONITOR_HENGTONG_LIMIT_S_DESC
              value: "{{ .Values.adminWeb.env.illegalMonitorHengtongLimitSDesc }}"
            - name: REACT_APP_ILLEGAL_MONITOR_XINDIAN_LIMIT
              value: "{{ .Values.adminWeb.env.illegalMonitorXindianLimit }}"
            - name: REACT_APP_ILLEGAL_MONITOR_XINDIAN_LIMIT_S
              value: "{{ .Values.adminWeb.env.illegalMonitorXindianLimitS }}"
            - name: REACT_APP_ILLEGAL_MONITOR_XINDIAN_LIMIT_S_DESC
              value: "{{ .Values.adminWeb.env.illegalMonitorXindianLimitSDesc }}"
            - name: REACT_APP_LOGIN_FAIL_LOCK_TIME_M
              value: "{{ .Values.adminWeb.env.loginFailLockTimeM }}"
            - name: REACT_APP_MAP_BOUND_LEFT
              value: "{{ .Values.adminWeb.env.mapBoundLeft }}"
            - name: REACT_APP_MAP_BOUND_RIGHT
              value: "{{ .Values.adminWeb.env.mapBoundRight }}"
            - name: REACT_APP_MAP_CENTER
              value: "{{ .Values.adminWeb.env.mapCenter }}"
            - name: REACT_APP_MAP_CURRENT_ZOOM
              value: "{{ .Values.adminWeb.env.mapCurrentZoom }}"
            - name: REACT_APP_MAP_ENDPOINT
              value: "{{ .Values.adminWeb.env.mapEndpoint }}"
            - name: REACT_APP_MAP_GANTRY_MIN_ZOOM
              value: "{{ .Values.adminWeb.env.mapGantryMinZoom }}"
            - name: REACT_APP_MAP_MAX_ZOOM
              value: "{{ .Values.adminWeb.env.mapMaxZoom }}"
            - name: REACT_APP_MAP_MIN_ZOOM
              value: "{{ .Values.adminWeb.env.mapMinZoom }}"
            - name: REACT_APP_MQTT_HOSTNAME
              value: "{{ .Values.adminWeb.env.mqttHostname }}"
            - name: REACT_APP_MQTT_HOSTNAME_EMPTY
              value: "{{ .Values.adminWeb.env.mqttHostnameEmpty }}"
            - name: REACT_APP_MQTT_PATH
              value: "{{ .Values.adminWeb.env.mqttPath }}"
            - name: REACT_APP_MQTT_PORT
              value: "{{ .Values.adminWeb.env.mqttPort }}"
            - name: REACT_APP_MQTT_PROTOCOL
              value: "{{ .Values.adminWeb.env.mqttProtocol }}"
            - name: REACT_APP_MQTT_TOPIC_ILLEGAL_MONITOR
              value: "{{ .Values.adminWeb.env.mqttTopicIllegalMonitor }}"
            - name: REACT_APP_MQTT_TOPIC_NOTIFY_WARNING
              value: "{{ .Values.adminWeb.env.mqttTopicNotifyWarning }}"
            - name: REACT_APP_OSS_ACCESS_KEY_ID
              value: "{{ .Values.adminWeb.env.ossAccessKeyId }}"
            - name: REACT_APP_OSS_ACCESS_KEY_SECRET
              value: "{{ .Values.adminWeb.env.ossAccessKeySecret }}"
            - name: REACT_APP_OSS_BUCKET
              value: "{{ .Values.adminWeb.env.ossBucket }}"
            - name: REACT_APP_OSS_EP_HOSTNAME
              value: "{{ .Values.adminWeb.env.ossEpHostname }}"
            - name: REACT_APP_OSS_EP_HOSTNAME_EMPTY
              value: "{{ .Values.adminWeb.env.ossEpHostnameEmpty }}"
            - name: REACT_APP_OSS_EP_PORT
              value: "{{ .Values.adminWeb.env.ossEpPort }}"
            - name: REACT_APP_OSS_EP_PROTOCOL
              value: "{{ .Values.adminWeb.env.ossEpProtocol }}"
            - name: REACT_APP_OSS_FORCE_PATH_STYLE
              value: "{{ .Values.adminWeb.env.ossForcePathStyle }}"
            - name: REACT_APP_OSS_REGION
              value: "{{ .Values.adminWeb.env.ossRegion }}"
            - name: REACT_APP_PAGE_MAX_WIDTH
              value: "{{ .Values.adminWeb.env.pageMaxWidth }}"
            - name: REACT_APP_PROVIDER
              value: "{{ .Values.adminWeb.env.provider }}"
            - name: REACT_APP_SCOPE
              value: "{{ .Values.adminWeb.env.scope }}"
            - name: REACT_APP_SUB_TITLE
              value: "{{ .Values.adminWeb.env.subTitle }}"
            - name: REACT_APP_TITLE
              value: "{{ .Values.adminWeb.env.title }}"
            - name: REACT_APP_VERSION
              value: "{{ .Values.adminWeb.env.version }}"
            - name: REACT_APP_WARNING_CARD_MAX_SIZE
              value: "{{ .Values.adminWeb.env.warningCardMaxSize }}"
            - name: REACT_APP_WARNING_TRACK_FLASH_S
              value: "{{ .Values.adminWeb.env.warningTrackFlashS }}"
          ports:
            - name: http
              containerPort: {{ .Values.adminWeb.service.port | default .Values.service.port }}
              protocol: TCP
          resources:
            {{- if .Values.adminWeb.resources }}
            {{- toYaml .Values.adminWeb.resources | nindent 12 }}
            {{- else }}
            {{- toYaml .Values.resources | nindent 12 }}
            {{- end }}
{{- end }}