{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.name }}
  labels:
    {{- include "api.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type | default .Values.service.type }}
  ports:
    - port: {{ .Values.api.service.port | default .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "api.selectorLabels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api.name }}
  labels:
    {{- include "fcp-ecs.labels" . | nindent 4 }}
    {{- include "api.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicas }}
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "api.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Values.api.name }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy | default .Values.pullPolicy }}
          env:
            - name: CACHE_REDIS_DB
              value: "{{ .Values.api.env.cacheRedisDb }}"
            - name: CACHE_REDIS_URL
              value: "{{ .Values.api.env.cacheRedisUri }}"
            - name: CHECK_TIME
              value: "{{ .Values.api.env.checkTime }}"
            - name: ILLEGAL_EXPIRES
              value: "{{ .Values.api.env.illegalExpires }}"
            - name: ILLEGAL_EXPIRES_DAYS
              value: "{{ .Values.api.env.illegalExpiresDays }}"
            - name: ILLEGAL_IGNORE_UNDERSPEED
              value: "{{ .Values.api.env.illegalIgnoreUnderspeed }}"
            - name: ILLEGAL_MONITOR
              value: "{{ .Values.api.env.illegalMonitor }}"
            - name: ILLEGAL_OVERSPEED_CODE
              value: "{{ .Values.api.env.illegalOverspeedCode }}"
            - name: ILLEGAL_RECORD_CLEAN
              value: "{{ .Values.api.env.illegalRecordClean }}"
            - name: ILLEGAL_TO_XINDIAN
              value: "{{ .Values.api.env.illegalToXindian }}"
            - name: ILLEGAL_TO_XINDIAN_LIMIT
              value: "{{ .Values.api.env.illegalToXindianLimit }}"
            - name: ILLEGAL_UNDERSPEED_CODE
              value: "{{ .Values.api.env.illegalUnderspeedCode }}"
            - name: ILLEGAL_UNDERSPEED_LIMIT
              value: "{{ .Values.api.env.illegalUnderspeedLimit }}"
            - name: INIT_CACHE
              value: "{{ .Values.api.env.initCache }}"
            - name: LOG_LEVEL
              value: "{{ .Values.api.env.logLevel }}"
            - name: MICROSERVICE_ENABLE
              value: "{{ .Values.api.env.microserviceEnable }}"
            - name: MONGO_URL
              value: "{{ .Values.api.env.mongoUri }}"
            - name: MQTT_CLIENT
              value: "{{ .Values.api.env.mqttClient }}"
            - name: MQTT_PASSWORD
              value: "{{ .Values.api.env.mqttPassword }}"
            - name: MQTT_TOPIC_DEVICE_CREATE
              value: "{{ .Values.api.env.mqttTopicDeviceCreate }}"
            - name: MQTT_TOPIC_DEVICE_DELETE
              value: "{{ .Values.api.env.mqttTopicDeviceDelete }}"
            - name: MQTT_TOPIC_DEVICE_STATUS
              value: "{{ .Values.api.env.mqttTopicDeviceStatus }}"
            - name: MQTT_TOPIC_DEVICE_UPDATE
              value: "{{ .Values.api.env.mqttTopicDeviceUpdate }}"
            - name: MQTT_TOPIC_ILLEGAL_RECORD
              value: "{{ .Values.api.env.mqttTopicIllegalRecord }}"
            - name: MQTT_TOPIC_ILLEGAL_RECORD_DAHUA
              value: "{{ .Values.api.env.mqttTopicIllegalRecordDahua }}"
            - name: MQTT_TOPIC_ILLEGAL_RECORD_MONITOR
              value: "{{ .Values.api.env.mqttTopicIllegalRecordMonitor }}"
            - name: MQTT_TOPIC_NOTIFY_ILLEGAL_XINDIAN
              value: "{{ .Values.api.env.mqttTopicNotifyIllegalXindian }}"
            - name: MQTT_TOPIC_NOTIFY_WARNING
              value: "{{ .Values.api.env.mqttTopicNotifyWarning }}"
            - name: MQTT_TOPIC_NOTIFY_WARNING_JINGWUTONG
              value: "{{ .Values.api.env.mqttTopicNotifyWarningJingwutong }}"
            - name: MQTT_TOPIC_TRACK_RECORD
              value: "{{ .Values.api.env.mqttTopicTrackRecord }}"
            - name: MQTT_TOPIC_TRACK_RECORD_DAHUA
              value: "{{ .Values.api.env.mqttTopicTrackRecordDahua }}"
            - name: MQTT_TOPIC_WARNING_CLOSE
              value: "{{ .Values.api.env.mqttTopicWarningClose }}"
            - name: MQTT_URL
              value: "{{ .Values.api.env.mqttUri }}"
            - name: MQTT_USERNAME
              value: "{{ .Values.api.env.mqttUsername }}"
            - name: PORT
              value: "{{ .Values.api.env.port }}"
            - name: TRACK_RECORD_CLEAN
              value: "{{ .Values.api.env.trackRecordClean }}"
            - name: URL_PREFIX
              value: "{{ .Values.api.path }}"
            - name: VEHICLE_IMPORT_CLEAN
              value: "{{ .Values.api.env.vehicleImportClean }}"
            - name: VEHICLE_IMPORT_DELAY
              value: "{{ .Values.api.env.vehicleImportDelay }}"
            - name: VEHICLE_IMPORT_LIMIT
              value: "{{ .Values.api.env.vehicleImportLimit }}"
            - name: VEHICLE_IMPORT_PATH
              value: "{{ .Values.api.env.vehicleImportPath }}"
            - name: WARNING_CLEAN
              value: "{{ .Values.api.env.warningClean }}"
            - name: WARNING_EXPIRES
              value: "{{ .Values.api.env.warningExpires }}"
          ports:
            - name: http
              containerPort: {{ .Values.api.service.port | default .Values.service.port }}
              protocol: TCP
          resources:
            {{- if .Values.api.resources }}
            {{- toYaml .Values.api.resources | nindent 12 }}
            {{- else }}
            {{- toYaml .Values.resources | nindent 12 }}
            {{- end }}
{{- end }}