{{- if .Values.ingress.enabled -}}
{{- $fullName := include "fcp-ecs.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "fcp-ecs.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    {{- if .Values.adminWeb.enabled }}
    - http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: admin-web
                port:
                  number: 80
      {{- if .Values.host }}
      host: {{ .Values.host | quote}}
      {{- end }}
    {{- end }}
    {{- if .Values.api.enabled }}
    - http:
        paths:
          - path: {{ .Values.api.path }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: api
                port:
                  number: 80
      {{- if .Values.host }}
      host: {{ .Values.host | quote}}
      {{- end }}
    {{- end }}
    {{- if .Values.auth.enabled }}
    - http:
        paths:
          - path: {{ .Values.auth.path }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: auth
                port:
                  number: 80
      {{- if .Values.host }}
      host: {{ .Values.host | quote}}
      {{- end }}
    {{- end }}
    {{- if .Values.robotDahua.enabled }}
    - http:
        paths:
          - path: {{ .Values.robotDahua.path }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.robotDahua.name }}
                port:
                  number: 80
      {{- if .Values.host }}
      host: {{ .Values.host | quote}}
      {{- end }}
    {{- end }}
{{- end }}
