{{- if .Values.roadmap.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.roadmap.name }}
  labels:
    {{- include "roadmap.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.roadmap.service.type | default .Values.service.type }}
  ports:
    - port: {{ .Values.roadmap.service.port | default .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "roadmap.selectorLabels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.roadmap.name }}
  labels:
    {{- include "fcp-ecs.labels" . | nindent 4 }}
    {{- include "roadmap.selectorLabels" . | nindent 4 }}
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "roadmap.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "roadmap.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Values.roadmap.name }}
          image: "{{ .Values.roadmap.image.repository }}:{{ .Values.roadmap.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.roadmap.image.pullPolicy | default .Values.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.roadmap.service.port | default .Values.service.port }}
              protocol: TCP
          resources:
            {{- if .Values.roadmap.resources }}
            {{- toYaml .Values.roadmap.resources | nindent 12 }}
            {{- else }}
            {{- toYaml .Values.resources | nindent 12 }}
            {{- end }}
{{- end }}