{{- if .Values.robotMock.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.robotMock.name }}
  labels:
    {{- include "robot-mock.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.robotMock.service.type | default .Values.service.type }}
  ports:
    - port: {{ .Values.robotMock.service.port | default .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "robot-mock.selectorLabels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.robotMock.name }}
  labels:
    {{- include "fcp-ecs.labels" . | nindent 4 }}
    {{- include "robot-mock.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.robotMock.replicas }}
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "robot-mock.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "robot-mock.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Values.robotMock.name }}
          image: "{{ .Values.robotMock.image.repository }}:{{ .Values.robotMock.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.robotMock.image.pullPolicy | default .Values.pullPolicy }}
          env:
            - name: LOG_LEVEL
              value: "{{ .Values.robotMock.env.logLevel }}"
            - name: MQTT_PASSWORD
              value: "{{ .Values.robotMock.env.mqttPassword }}"
            - name: MQTT_TOPIC_ILLEGAL_RECORD
              value: "{{ .Values.robotMock.env.mqttTopicIllegalRecord }}"
            - name: MQTT_TOPIC_TRACK_RECORD
              value: "{{ .Values.robotMock.env.mqttTopicTrackRecord }}"
            - name: MQTT_URL
              value: "{{ .Values.robotMock.env.mqttUri }}"
            - name: MQTT_USERNAME
              value: "{{ .Values.robotMock.env.mqttUsername }}"
            - name: NODE_ENV
              value: "{{ .Values.robotMock.env.nodeEnv }}"
            - name: PORT
              value: "{{ .Values.robotMock.env.port }}"
            - name: URL_PREFIX
              value: "{{ .Values.robotMock.env.urlPrefix }}"
            - name: API_SERVICE
              value: "{{ .Values.robotMock.env.apiService }}"
          ports:
            - name: http
              containerPort: {{ .Values.robotMock.service.port | default .Values.service.port }}
              protocol: TCP
          resources:
            {{- if .Values.robotMock.resources }}
            {{- toYaml .Values.robotMock.resources | nindent 12 }}
            {{- else }}
            {{- toYaml .Values.resources | nindent 12 }}
            {{- end }}
{{- end }}