{{ if .Values.robotHengtong.mock.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.robotHengtong.mock.name }}
  labels:
    {{- include "fcp-ecs.labels" . | nindent 4 }}
    {{- include "robot-hengtong-mock.selectorLabels" . | nindent 4 }}
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "robot-hengtong-mock.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "robot-hengtong-mock.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Values.robotHengtong.mock.name }}
          image: "{{ .Values.robotHengtong.image.repository }}:{{ .Values.robotHengtong.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.robotHengtong.image.pullPolicy | default .Values.pullPolicy }}
          env:
            - name: LOG_LEVEL
              value: "{{ .Values.robotHengtong.env.logLevel }}"
            - name: NAME
              value: "{{ .Values.robotHengtong.env.name }}"
            - name: SOURCE_NAME
              value: "{{ .Values.robotHengtong.env.sourceName }}"
            - name: ROBOT_ENDPOINT
              value: "{{ .Values.robotHengtong.env.robotEndpoint }}"
            - name: FCP_ENDPOINT
              value: "{{ .Values.robotHengtong.env.fcpEndpoint }}"
            - name: CACHE_REDIS_URL
              value: "{{ .Values.robotHengtong.env.redisUri }}"
            - name: MQTT_PASSWORD
              value: "{{ .Values.robotHengtong.env.mqttPassword }}"
            - name: REDIS_GLOBAL_PREFIX
              value: "{{ .Values.robotHengtong.env.redisGlobalPrefix }}"
            - name: DRAFT_EXPIRE_DAYS
              value: "{{ .Values.robotHengtong.env.draftExpireDays }}"
            - name: MQTT_TOPIC_ILLEGAL_RECORD
              value: "{{ .Values.robotHengtong.env.mqttTopicIllegalRecord }}"
            - name: MQTT_TOPIC_ILLEGAL_DRAFT
              value: "{{ .Values.robotHengtong.env.mqttTopicIllegalDraft }}"
            - name: MQTT_TOPIC_GANTRY_DEVICE
              value: "{{ .Values.robotHengtong.env.mqttTopicGantryDevice}}"
            - name: MQTT_TOPIC_GANTRY
              value: "{{ .Values.robotHengtong.env.mqttTopicGantry }}"
            - name: MQTT_TOPIC_ILLEGAL_TYPE
              value: "{{ .Values.robotHengtong.env.mqttTopicIllegalType }}"
            - name: MQTT_URL
              value: "{{ .Values.robotHengtong.env.mqttUri }}"
            - name: MQTT_USERNAME
              value: "{{ .Values.robotHengtong.env.mqttUsername }}"
            - name: NODE_ENV
              value: "{{ .Values.robotHengtong.env.nodeEnv }}"
            - name: PORT
              value: "{{ .Values.robotHengtong.env.port }}"
            - name: URL_PREFIX
              value: "{{ .Values.robotHengtong.path }}"
          command: ["pnpm", "mock:prod"]
          ports:
            - name: http
              containerPort: {{ .Values.robotHengtong.service.port | default .Values.service.port }}
              protocol: TCP
          resources:
            {{- if .Values.robotHengtong.resources }}
            {{- toYaml .Values.robotHengtong.resources | nindent 12 }}
            {{- else }}
            {{- toYaml .Values.resources | nindent 12 }}
            {{- end }}
{{- end }}