{{- if .Values.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "offline-map.fullname" . }}
  labels: 
    {{- include "offline-map.labels" . | nindent 4 }}
    app.kubernetes.io/component: offline-map
  annotations: 
    {{- .Values.persistence.annotations | toYaml | nindent 4 }}
spec:
  accessModes:
  {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- include "offline-map.storage.class" (dict "persistence" .Values.persistence "global" .Values.global) | nindent 2 }}
{{- end }}