apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "offline-map.labels" . | nindent 4 }}
    app.kubernetes.io/component: offline-map
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: 
    {{- include "offline-map.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: offline-map