{{- if .Values.trackAnalysisRobot.enabled }}
{{- $endpoint := include "fcp.endpoint" .Values.trackAnalysisRobot -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.trackAnalysisRobot.name }}
  labels:
    {{- include "fcp.labels" . | nindent 4 }}
    app.kubernetes.io/component: track-analysis-robot
spec:
  replicas: {{ .Values.trackAnalysisRobot.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "fcp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: track-analysis-robot
  template:
    metadata:
      {{- with .Values.trackAnalysisRobot.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fcp.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: track-analysis-robot
    spec:
      {{- include "fcp.images.pullSecrets" (dict "images" (list .Values.trackAnalysisRobot.image) "global" .Values.global) | nindent 6 }}
      initContainers:
        - name: wait-for-core
          image: busybox:1.28
          command: ['sh', '-c', 'until nslookup {{ .Values.core.name }}; do echo waiting for core service ready; sleep 10; done;']
      containers:
        - name: track-analysis-robot
          image: {{ include "fcp.images.image" ( dict "imageRoot" .Values.trackAnalysisRobot.image "global" .Values.global ) }}
          imagePullPolicy: {{ .Values.trackAnalysisRobot.image.pullPolicy | default .Values.global.imagePullPolicy }}
          env:
            - name: URL_PREFIX
              value: {{ .Values.trackAnalysisRobot.path }}
            - name: ROBOT_ENDPOINT
              value: {{ $endpoint }}
            - name: FCP_ENDPOINT
              value: http://{{ .Values.core.name }}{{ .Values.core.path }}
            {{- range $key, $value := .Values.trackAnalysisRobot.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            {{- toYaml .Values.trackAnalysisRobot.resources | nindent 12 }}
      {{- with .Values.trackAnalysisRobot.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.trackAnalysisRobot.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.trackAnalysisRobot.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}