apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "roadmap.name" . }}
  labels:
    {{- include "roadmap.labels" . | nindent 4 }}
    app.kubernetes.io/component: roadmap
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "roadmap.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: roadmap
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "roadmap.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: roadmap
    spec:
      {{- include "roadmap.images.pullSecrets" (dict "images" (list .Values.image) "global" .Values.global) | nindent 6 }}
      containers:
        - name: roadmap
          image: {{ include "roadmap.images.image" ( dict "imageRoot" .Values.image "global" .Values.global ) }}
          imagePullPolicy: {{ .Values.image.pullPolicy | default .Values.global.imagePullPolicy }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value }}
            {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
