apiVersion: v1
kind: Service
metadata:
  name: {{ include "roadmap.name" . }}
  labels:
    {{- include "roadmap.labels" . | nindent 4 }}
    app.kubernetes.io/component: roadmap
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: 
    {{- include "roadmap.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: roadmap