{{- if .Values.adminWeb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.adminWeb.name }}
  labels:
    {{- include "admin-web.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.adminWeb.service.type | default .Values.service.type }}
  ports:
    - port: {{ .Values.adminWeb.service.port | default .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "admin-web.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.name }}
  labels:
    {{- include "api.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type | default .Values.service.type }}
  ports:
    - port: {{ .Values.api.service.port | default .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "api.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.auth.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.auth.name }}
  labels:
    {{- include "auth.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.auth.service.type | default .Values.service.type }}
  ports:
    - port: {{ .Values.auth.service.port | default .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "auth.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{ if .Values.robotHengtong.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.robotHengtong.name }}
  labels:
    {{- include "robot-hengtong.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.robotHengtong.service.type | default .Values.service.type }}
  ports:
    - port: {{ .Values.robotHengtong.service.port | default .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "robot-hengtong.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.robotXindian.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.robotXindian.name }}
  labels:
    {{- include "robot-xindian.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.robotXindian.service.type | default .Values.service.type }}
  ports:
    - port: {{ .Values.robotXindian.service.port | default .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "robot-xindian.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.robotXindian2.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.robotXindian2.name }}
  labels:
    {{- include "robot-xindian2.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.robotXindian2.service.type | default .Values.service.type }}
  ports:
    - port: {{ .Values.robotXindian2.service.port | default .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "robot-xindian2.selectorLabels" . | nindent 4 }}
{{- end }}
