{{- if .Values.authNew.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.authNew.name }}
  labels:
    {{- include "fcp.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth-new
spec:
  replicas: {{ .Values.authNew.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "fcp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: auth-new
  template:
    metadata:
      {{- with .Values.authNew.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fcp.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: auth-new
    spec:
      {{- include "fcp.images.pullSecrets" (dict "images" (list .Values.authNew.image) "global" .Values.global) | nindent 6 }}
      containers:
        - name: {{ .Values.authNew.name }}
          image: {{ include "fcp.images.image" ( dict "imageRoot" .Values.authNew.image "global" .Values.global ) }}
          imagePullPolicy: {{ .Values.authNew.image.pullPolicy | default .Values.global.imagePullPolicy }}
          env:
            - name: PREFIX
              value: {{ .Values.authNew.path }}
            {{- range $key, $value := .Values.authNew.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          ports:
            - name: http
              containerPort: 9527
              protocol: TCP
          resources:
            {{- toYaml .Values.authNew.resources | nindent 12 }}
      {{- with .Values.authNew.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.authNew.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.authNew.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
