{{- if .Values.auth-new.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.auth-new.name }}
  labels:
    {{- include "fcp.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth-new
spec:
  type: {{ .Values.auth-new.service.type | default .Values.service.type }}
  ports:
    - port: {{ .Values.auth-new.service.port | default .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fcp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: auth-new
{{- end }}
