{{- if .Values.platform.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.platform.name }}
  labels:
    {{- include "fcp.labels" . | nindent 4 }}
    app.kubernetes.io/component: platform
spec:
  replicas: {{ .Values.platform.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "fcp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: platform
  template:
    metadata:
      {{- with .Values.platform.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fcp.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: platform
    spec:
      {{- include "fcp.images.pullSecrets" (dict "images" (list .Values.platform.image) "global" .Values.global) | nindent 6 }}
      containers:
        - name: {{ .Values.platform.name }}
          image: {{ include "fcp.images.image" ( dict "imageRoot" .Values.platform.image "global" .Values.global ) }}
          imagePullPolicy: {{ .Values.platform.image.pullPolicy | default .Values.global.imagePullPolicy }}
          env:
            {{- range $key, $value := .Values.platform.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            {{- toYaml .Values.platform.resources | nindent 12 }}
      {{- with .Values.platform.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.platform.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.platform.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}